name: Chaining Jobs

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Job 1 Step
      run: echo "This is Job 1"

  job2:
    needs: job1 
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' }} # Executa apenas se o push for na branch main
    steps:
    - name: Job 2 Step
      run: echo "This is Job 2"

  job3:
    needs: job2 
    runs-on: ubuntu-latest
    if: ${{ always() }} # Este job será executado independentemente do sucesso ou falha dos jobs anteriores
    steps:
    - name: Job 3 Step
      run: echo "This is Job 3"

  job4:
    needs: job3 
    runs-on: ubuntu-latest
    if: ${{ failure() }} # Este job será executado apenas se algum dos jobs anteriores falhar
    steps:
    - name: Job 4 Step
      run: echo "This is Job 4"
